import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';

import { LOCALES, Locale, NS_LIST, initTranslations } from '@/lib';
import { setLocale } from '@/lib/context';
import '../globals.css';
import { ParamsProps } from '@/types';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<PropsWithChildren<ParamsProps<{ locale: Locale }>>>) {
  setLocale(locale);
  // eslint-disable-next-line no-unused-vars
  const { resources } = await initTranslations(locale, NS_LIST);
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
